name: plant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  table_calendar: ^3.0.9
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Modak
      fonts:
        - asset: assets/fonts/Modak-Regular.ttf
  assets:
    - assets/images/
